apiVersion: v1
kind: Service
metadata:
    name: app-service
    labels:
        app: clickhouse-playground
        component: app
spec:
    type: NodePort
    ports:
      - port: 3999
        protocol: TCP
        nodePort: 30002
        targetPort: 8080
    selector:
        app: clickhouse-playground
        component: app
---    
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-deployment
spec:
    selector:
        matchLabels:
            app: clickhouse-playground
            component: app
    replicas: 1
    template:
        metadata:
            labels:
                app: clickhouse-playground
                component: app
        spec:
            containers:
              - name: app
                image: app
                imagePullPolicy: Never
                ports:
                  - containerPort: 8080
