
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-v20.9-consumer
  namespace: default
  labels:
    deploymentName: clickhouse-v20.9-deployment
spec:
  scaleTargetRef:
    deploymentName: clickhouse-v20.9-deployment
  pollingInterval: 2 # Optional. Default: 30 seconds
  cooldownPeriod: 30 # Optional. Default: 300 seconds
  minReplicaCount: 1
  maxReplicaCount: 10 # Optional. Default: 100
  triggers:
    - type: rabbitmq
      metadata:
        queueName: execute-v20.9
        queueLength: "1" # TODO: research this param
      authenticationRef:
        name: rabbitmq-consumer-trigger
---

apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-v20.8-consumer
  namespace: default
  labels:
    deploymentName: clickhouse-v20.8-deployment
spec:
  scaleTargetRef:
    deploymentName: clickhouse-v20.8-deployment
  pollingInterval: 2 # Optional. Default: 30 seconds
  cooldownPeriod: 30 # Optional. Default: 300 seconds
  minReplicaCount: 1
  maxReplicaCount: 10 # Optional. Default: 100
  triggers:
    - type: rabbitmq
      metadata:
        queueName: execute-v20.8
        queueLength: "1" # TODO: research this param
      authenticationRef:
        name: rabbitmq-consumer-trigger
---

