{{range .Versions}}
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-{{.Id}}-consumer
  namespace: default
  labels:
    deploymentName: clickhouse-{{.Id}}-deployment
spec:
  scaleTargetRef:
    deploymentName: clickhouse-{{.Id}}-deployment
  pollingInterval: 2 # Optional. Default: 30 seconds
  cooldownPeriod: 30 # Optional. Default: 300 seconds
  minReplicaCount: 1
  maxReplicaCount: 10 # Optional. Default: 100
  triggers:
    - type: rabbitmq
      metadata:
        queueName: execute-{{.Id}}
        queueLength: "1" # TODO: research this param
      authenticationRef:
        name: rabbitmq-consumer-trigger
---
{{end}}
