apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-deployment
spec:
  selector:
    matchLabels:
      app: clickhouse-playground
      component: executor
  replicas: 1
  template:
    metadata:
      labels:
        app: clickhouse-playground
        component: executor
    spec:
      shareProcessNamespace: true
      containers:
      - name: clickhouse-executor
        image: gcr.io/avid-life-273910/executor
      - name: clickhouse-server
        image: yandex/clickhouse-server:20.7.2.30
        ports:
        - containerPort: 8080
