version: '3.7'
services:
  db:
    image: yandex/clickhouse-server 
    ports: 
    - "8123:8123"
    - "9000:9000"
  # client:
  #   image: yandex/clickhouse-server
  #   depends_on:
  #   - db    
  #   stdin_open: true
  #   tty: true
  server:
    build:
      context: app
    ports:
    - "3999:8080"
    depends_on: 
    - db
  frontend:
    build:
      context: frontend
    volumes:
      - "/app/node_modules"
      - "./frontend:/app"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server

