version: '3.7'
services:
  db:
    image: yandex/clickhouse-server 
    ports: 
    - "8120:8123"
    # - "9000:9000"
  # client:
  #   image: yandex/clickhouse-server
  #   depends_on:
  #   - db    
  #   stdin_open: true
  #   tty: true
  backend:
    build:
      context: app
    ports:
    - "3999:8080"
    volumes: 
    - "/var/run/docker.sock:/var/run/docker.sock"
    # depends_on: 
    # - db
    # links:
    # - db
  frontend:
    build:
      context: ./frontend/project
    volumes:
      - "./frontend/project/:/install/app/"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    links:
      - backend

