{{range .Versions}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-{{.Id}}-deployment
spec:
  selector:
    matchLabels:
      app: clickhouse-playground
      component: executor
      versionId: {{.Id}}
  replicas: 1
  template:
    metadata:
      labels:
        app: clickhouse-playground
        component: executor
        versionId: {{.Id}}
    spec:
      shareProcessNamespace: true
      containers:
      - name: clickhouse-executor
        image: gcr.io/avid-life-273910/executor
        env:
        - name: RECEIVE_QUEUE_NAME
          value: execute-{{.Id}}
        - name: IMAGE_VERSION
          value: "20.9"
      - name: clickhouse-server
        image: yandex/clickhouse-server:latest
      #   ports:
      #   - containerPort: 8123
      #     protocol: 'TCP'
      #   - containerPort: 9000
      #     protocol: 'TCP'
      #   - containerPort: 9004
      #     protocol: 'TCP'
      #   - containerPort: 9009
      #     protocol: 'TCP'
---
{{end}}
